/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatterclient;

import JavaBeans.Message;
import JavaBeans.User;
import TabPaneHandler.CustomTabePane;
import java.awt.Component;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.Socket;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.Map.Entry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import socketHandler.ClientSocketHandler;
import socketHandler.*;

/**
 *
 * @author ahmedsobhy
 */
public class MainPage extends javax.swing.JFrame implements interfaceobserver.MessageListener {

    ClientSocketHandler handler;
    String friendmail;
    DefaultListModel<String> friendListModel;
    DefaultListModel<String> groupListModel;
    public ArrayList<String> emails;
    User user;
    int index;
    CustomTabePane tabFriendList, tabGroupList;
    boolean f;
    public LinkedHashMap<Integer, CustomTabePane> tabs;

    /**
     * Creates new form MainPage
     */
    public MainPage(ClientSocketHandler handler) {
        initComponents();
        this.handler = handler;
        emails = new ArrayList<String>();
        usrNameLbl.setText(getUserNamelbl());

        friendListModel = new DefaultListModel<>();
        friendList.setModel(friendListModel);
        friendListModel.addElement(userName);

        groupListModel = new DefaultListModel<>();
        groupList.setModel(groupListModel);
        groupListModel.addElement(userName);
        user = User.getInstance();
        tabs = new LinkedHashMap<>();
    }

    /* set and get for the friend */
    public void setFriendListModel(String friendListX) {
        //this.friendList1 = friendList1;
        friendListModel.addElement(friendListX);
    }

    public DefaultListModel<String> getFriendListModel() {
        return friendListModel;
    }

    /* set and get for the group */
    public void setGroupListModel(String groupListX) {
        //this.groupListModel = groupListModel;
        groupListModel.addElement(groupListX);
    }

    public DefaultListModel<String> getGroupListModel() {
        return groupListModel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        usrNameLbl = new javax.swing.JLabel();
        mainTabPane = new javax.swing.JTabbedPane();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        addFriendBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Cntctlbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        friendList = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        grplbl = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        groupList = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setLayout(new java.awt.BorderLayout(3, 3));

        usrNameLbl.setText("User Name");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Online", "Offline", "Busy", "Away" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton4.setText("Create Group");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        addFriendBtn.setText("Add Friend");
        addFriendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFriendBtnActionPerformed(evt);
            }
        });

        Cntctlbl.setText("Contact List");

        friendList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        friendList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                friendListMouseClicked(evt);
            }
        });
        friendList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                friendListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(friendList);

        grplbl.setText("Groups");

        groupList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        groupList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                groupListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(groupList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cntctlbl)
                            .addComponent(grplbl)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Cntctlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(grplbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(mainTabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addFriendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))
                        .addGap(95, 95, 95))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usrNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(mainTabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(usrNameLbl)
                                .addGap(26, 26, 26)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(addFriendBtn)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(112, 112, 112))))
        );

        MainPanel.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jMenu1.setText("Control");

        jMenuItem1.setMnemonic('O');
        jMenuItem1.setText("Sign-out");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Themes");

        jMenuItem4.setText("Metal");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Unix");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Help");

        jMenuItem3.setText("About us");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        SwingUtilities.updateComponentTreeUI(this);
        this.pack();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void friendListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_friendListValueChanged

        //Open new taaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaappppp

    }//GEN-LAST:event_friendListValueChanged

    private void addFriendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFriendBtnActionPerformed

        JFrame frame = new JFrame();
        friendmail = JOptionPane.showInputDialog(
                frame,
                "Enter you friend here",
                "Add friend ",
                JOptionPane.PLAIN_MESSAGE
        );

        handler.ps.println("4" + "$" + friendmail);

    }//GEN-LAST:event_addFriendBtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false);

        new controlGroup().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // show a joptionpane dialog using showMessageDialog
        JOptionPane.showMessageDialog(this,
                "AMS-Team .. Open Source .. Intake 36 .. Nozha Branch.",
                "About Us...",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem3ActionPerformed


    private void friendListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_friendListMouseClicked
        PanelCreation panel = new PanelCreation();
        tabFriendList = new CustomTabePane(mainTabPane, friendList, this.friendList.getSelectedIndex(), panel);

        if (tabs.isEmpty()) {
            tabFriendList.addTab();
            tabs.put(this.friendList.getSelectedIndex(), tabFriendList);
        } else {
            for (Entry<Integer, CustomTabePane> entry : tabs.entrySet()) {
                System.out.println("sss");
                System.out.println("key" + entry.getKey());
                System.out.println("item index" + this.friendList.getSelectedIndex());
                if (entry.getKey() == this.friendList.getSelectedIndex()) {
                    f = false;
                    System.out.println(f);
                    break;
                } else {
                    f = true;
                    System.out.println(f);
                }
            }
            System.out.println("f >>" + f);
            if (f == true) {
                tabFriendList.addTab();
                tabs.put(this.friendList.getSelectedIndex(), tabFriendList);
                System.out.println("f=false");
            }
        }
        System.out.println("end");
    }//GEN-LAST:event_friendListMouseClicked

    private void groupListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupListMouseClicked
       // tabGroupList = new CustomTabePane(mainTabPane, groupList, index, panel);
        //tabGroupList.addTab();
    }//GEN-LAST:event_groupListMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        try {
            UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
            this.pack();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    public void setUserNamelbl(String name) {
        //userName=name;

        this.usrNameLbl.setText(name);
    }

    String userName;

    String getUserNamelbl() {
        return userName;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cntctlbl;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton addFriendBtn;
    private javax.swing.JList<String> friendList;
    private javax.swing.JList<String> groupList;
    private javax.swing.JLabel grplbl;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane mainTabPane;
    private javax.swing.JLabel usrNameLbl;
    // End of variables declaration//GEN-END:variables
class PanelCreation extends JPanel {

        private javax.swing.JButton sendMsgBtn;
        private javax.swing.JButton sendFileBtn;
        private javax.swing.JTextArea msgTA;
        private javax.swing.JTextArea chatMsgs;
        private javax.swing.JScrollPane jScrollPane5;
        private javax.swing.JScrollPane jScrollPane4;
        JPanel panelbtn,msgPanel,msgsPanel;
        public PanelCreation() {

            chatMsgs = new javax.swing.JTextArea();
            msgTA = new javax.swing.JTextArea();
            sendMsgBtn = new javax.swing.JButton();
            jScrollPane5 = new javax.swing.JScrollPane(msgTA);
            jScrollPane4 = new javax.swing.JScrollPane(chatMsgs);
            sendFileBtn = new javax.swing.JButton();
            panelbtn=new JPanel();
            msgPanel=new JPanel(new GridLayout(1,2));
            msgsPanel=new JPanel();
            
            msgTA.setColumns(18);
            msgTA.setRows(3);
            
            chatMsgs.setEditable(false);
            chatMsgs.setColumns(39);
            chatMsgs.setRows(5);
           
            this.setLayout(new GridLayout(3,3));
            this.add(msgsPanel);           
            this.add(msgPanel);
            this.add(panelbtn);
            msgTA.setAlignmentX(CENTER_ALIGNMENT);
            
            msgsPanel.add(jScrollPane4);
            msgPanel.add(jScrollPane5);
            msgPanel.add(panelbtn);
            panelbtn.add(sendMsgBtn);
            sendMsgBtn.setSize(30, 20);
            sendMsgBtn.setText("Send");
            sendMsgBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    sendMsgBtnActionPerformed(evt);
                }
            });       
        }

        public void addPanel() {

        }

        private void sendMsgBtnActionPerformed(java.awt.event.ActionEvent evt) {

            //send if the index belong to friend list only....
            String msg = msgTA.getText();

            String from = user.getEmail();
            String to = emails.get(tabFriendList.index - 1);

            chatMsgs.setText(chatMsgs.getText() +userName+" :" + msg+"\n");

            try {
                handler.ps.println("2" + msg + "$" + from + "$" + to);
            } catch (Exception e) {
                System.out.println("error...");
            }
            System.out.println(emails.get(tabFriendList.index - 1));
            System.out.println(tabFriendList.index);

        }
    }

     String msg2;
     
//     private int valueToIndex(JList list, String value) {
// 	
//         int size = list.getModel().getSize();
// 	
//         for (int i=0;i < size;i++) {
// 	
//             String str = list.(list, i);
// 	
//             if (ExtendedComparator.stringsMatch(value, str)) {
// 	
//                 return i;
// 	  	
//             }
// 	  	
//         }
// 
//         return -1;
//   	
//     }
     
    @Override
    public void receiveMessage() {
        System.out.println("law el tab maffto7aa append --- else eft7 el tab bta3 ely b3t el msg");
        System.out.println("end");
        PanelCreation panel = new PanelCreation();        
        String m=Message.getMessage();
        System.out.println(" message : " + m);
        String[] parts = m.split("\\$");
        String msg1 = parts[0];
        String from = parts[1];
        String to= parts[2];
        
        
//        friendList.get
        System.out.println("tab opening");
        CustomTabePane cjp = new CustomTabePane(mainTabPane,friendList,0,panel);
        cjp.addTab(from);
        JOptionPane.showMessageDialog(mainTabPane,from+":"+msg1,"New Message Received",JOptionPane.PLAIN_MESSAGE);

//        CustomTabePane tabFriendList = new CustomTabePane(mainTabPane, friendList,2, panel);
//        System.out.println(index);
//        this.tabFriendList.addTab("mm");
//        System.out.println("endTab");
        
        /*
        if (tabs.isEmpty()) {
            tabFriendList.addTab();
            tabs.put(this.friendList.getSelectedIndex(), tabFriendList);
        } else {
            for (Entry<Integer, CustomTabePane> entry : tabs.entrySet()) {
                System.out.println("sss");
                System.out.println("key" + entry.getKey());
                System.out.println("item index" + this.friendList.getSelectedIndex());
                if (entry.getKey() == this.friendList.getSelectedIndex()) {
                    f = false;
                    System.out.println(f);
                    break;
                } else {
                    f = true;
                    System.out.println(f);
                }
            }
            System.out.println("f >>" + f);
            if (f == true) {
                tabFriendList.addTab();
                tabs.put(this.friendList.getSelectedIndex(), tabFriendList);
                System.out.println("f=false");
            }
        }
        System.out.println("end");
        //
*/
    }


    
}
