/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatterserver;

import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import serverOperation.ServerOperation;
import serverSocketHandler.ServerSocketHandler;

/**
 *
 * @author ahmedsobhy
 */
public class MainPage extends javax.swing.JFrame {

    ServerSocketHandler handler;
    serverOperation.ServerOperation operationObj;
    DBConnections.DBConnection dbConn;
    
    DefaultListModel<String> onlineListModel ;
    DefaultListModel<String> offlineListModel;
    

    
    public String anouncmentMsgStr;

    String modelItemString;
    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();

        onlineListModel = new DefaultListModel<>();
        onlineList.setModel(onlineListModel);
        onlineListModel.addElement(modelItemString);
        
        offlineListModel=new DefaultListModel<>();
        offlineList.setModel(offlineListModel);
        offlineListModel.addElement(modelItemString);

    }

    /* offline set and get  */
    
    public void setOnlineListModel(String onlineListX) {
     //   this.onlineListModel = onlineListModel;
    
     onlineListModel.addElement(onlineListX);
    //onlineListModel.set(onlineListX);
    }

    public DefaultListModel<String> getOnlineListModel() {
        return onlineListModel;
    }

    /* offline set and get */
    
    public void setOfflineListModel(String offlineListX) {
        //this.offlineListModel = offlineListModel;
        offlineListModel.addElement(offlineListX);
    }

    
    public DefaultListModel<String> getOfflineListModel() {
        return offlineListModel;
    }

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainTabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jToggleButton2 = new javax.swing.JToggleButton();
        serverStatusLbl = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        getall = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        maleLbl = new javax.swing.JLabel();
        femaleLbl = new javax.swing.JLabel();
        onLbl = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        countOnLbl = new javax.swing.JLabel();
        countOffLbl = new javax.swing.JLabel();
        offlineUsrCountLbl = new javax.swing.JLabel();
        onlineUsrCountLbl = new javax.swing.JLabel();
        getstatus = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        onlineList = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        offlineList = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        anouncmentMsgTF = new javax.swing.JTextField();
        sendAnouncmentBtn = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        info = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainTabbedPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainTabbedPaneMouseClicked(evt);
            }
        });

        jToggleButton2.setText("On/Off");
        jToggleButton2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton2ItemStateChanged(evt);
            }
        });
        jToggleButton2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButton2StateChanged(evt);
            }
        });
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        serverStatusLbl.setText("Server Status");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(serverStatusLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jToggleButton2)
                .addGap(29, 29, 29)
                .addComponent(serverStatusLbl)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        MainTabbedPane.addTab("Server Control", jPanel2);

        getall.setText("Refreash");
        getall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getallActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(56, 91, 176));
        jLabel3.setText("Current Online users : ");

        jLabel4.setForeground(new java.awt.Color(240, 38, 32));
        jLabel4.setText("Male :");

        jLabel5.setForeground(new java.awt.Color(41, 172, 46));
        jLabel5.setText("Female : ");

        maleLbl.setText("   ....");

        femaleLbl.setText(".....");

        onLbl.setText("......");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(50, 50, 50)
                                .addComponent(onLbl))
                            .addComponent(jLabel5)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(getall)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(femaleLbl)
                                .addComponent(maleLbl)))))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(onLbl))
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(maleLbl))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(femaleLbl))
                .addGap(35, 35, 35)
                .addComponent(getall)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        MainTabbedPane.addTab("Statistics", jPanel4);

        jLabel1.setText("Online Users");

        jLabel2.setText("Offline Users");

        countOnLbl.setText("count");

        countOffLbl.setText("count");

        offlineUsrCountLbl.setText("y");

        onlineUsrCountLbl.setText("x");

        getstatus.setText("Refreash");
        getstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getstatusActionPerformed(evt);
            }
        });

        onlineList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(onlineList);

        offlineList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(offlineList);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(getstatus))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(onlineUsrCountLbl)
                            .addComponent(countOnLbl))))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(offlineUsrCountLbl)
                    .addComponent(countOffLbl))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(countOffLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(offlineUsrCountLbl)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(countOnLbl))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(onlineUsrCountLbl)
                                .addGap(94, 94, 94)
                                .addComponent(getstatus))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 57, Short.MAX_VALUE))
        );

        MainTabbedPane.addTab("Online-Offline Users", jPanel5);

        sendAnouncmentBtn.setText("Send");
        sendAnouncmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendAnouncmentBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(anouncmentMsgTF, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sendAnouncmentBtn)
                .addContainerGap(224, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anouncmentMsgTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendAnouncmentBtn))
                .addContainerGap(260, Short.MAX_VALUE))
        );

        MainTabbedPane.addTab("Send Announcment", jPanel1);

        file.setText("File");

        jMenuItem1.setText("Exit");
        file.add(jMenuItem1);

        MenuBar.add(file);

        info.setText("Edit");
        MenuBar.add(info);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainTabbedPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MainTabbedPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainTabbedPaneMouseClicked
       


    }//GEN-LAST:event_MainTabbedPaneMouseClicked

    private void sendAnouncmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendAnouncmentBtnActionPerformed
        try {
            // TODO add your handling code here:
            anouncmentMsgStr = anouncmentMsgTF.getText();
            dbConn = new DBConnections.DBConnection();
            Statement stmt = dbConn.connection.createStatement();
            String getOnlineUsersQuery = "select user_id from users where status= 1 ";
            ResultSet rs = stmt.executeQuery(getOnlineUsersQuery);
            while (rs.next()) {
                int onlineUsersId = rs.getInt(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sendAnouncmentBtnActionPerformed

    private void jToggleButton2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButton2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2StateChanged

    private void jToggleButton2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jToggleButton2ItemStateChanged
        int statue = evt.getStateChange();
           
        if (statue == 1) {            
     
            serverStatusLbl.setText("Server On");
            handler = new ServerSocketHandler(12345);
           
        }
        else {
            // try {/ 
            serverStatusLbl.setText("Server Off");
            try {
                handler.ss.close();
                
                handler.suspend();
                
            } catch (Exception ex) {

            }

        }
    }//GEN-LAST:event_jToggleButton2ItemStateChanged

    private void getstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getstatusActionPerformed
        // TODO add your handling code here:
//         
       
       String onLineString  = new ServerOperation().getOnlineUsers();
       String offLineString = new ServerOperation().getOfflineUsers();
       
      
       onlineListModel.removeAllElements();
       offlineListModel.removeAllElements();
       
       
      
       String[] onlineArray = onLineString.split("\\*");
       String[] offlineArray= offLineString.split("\\*");
               
       int onlineLength = onlineArray.length;
       int offlineLength= offlineArray.length;
       
       
       for(int i=0 ; i<onlineLength ; i++){
           System.out.println(onlineArray[i]);
           setOnlineListModel(onlineArray[i]);
        } 

       for(int y=0 ; y<offlineLength ; y++){
           System.out.println(offlineArray[y]);
           setOfflineListModel(offlineArray[y]);
        } 
       
       StringBuilder on = new StringBuilder();
       on.append(onlineLength);
       String onn = on.toString();
       StringBuilder off = new StringBuilder();
       off.append(offlineLength);
       String offf = off.toString();
       
       onlineUsrCountLbl.setText(onn);
       offlineUsrCountLbl.setText(offf);
       
       //System.out.println(onlineLength);
       
       

    
    }//GEN-LAST:event_getstatusActionPerformed

    private void getallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getallActionPerformed
        // TODO add your handling code here:
        
         int male  = new ServerOperation().genderMaleStat();
         int female = new ServerOperation().genderFemaleStat();
         int online = new ServerOperation().getOnline();
         
          StringBuilder maleInteger = new StringBuilder();
          maleInteger.append(male);
          String malee = maleInteger.toString();
         
          
          StringBuilder femaleInteger = new StringBuilder();
          femaleInteger.append(female);
          String femalee = femaleInteger.toString();
          
          
           StringBuilder onlineInteger = new StringBuilder();
          onlineInteger.append(online);
          String onlinee = onlineInteger.toString();
          
          
          maleLbl.setText(malee);
          femaleLbl.setText(femalee);
          
          onLbl.setText(onlinee);
         
          
         
        
    }//GEN-LAST:event_getallActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane MainTabbedPane;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JTextField anouncmentMsgTF;
    private javax.swing.JLabel countOffLbl;
    private javax.swing.JLabel countOnLbl;
    private javax.swing.JLabel femaleLbl;
    private javax.swing.JMenu file;
    private javax.swing.JButton getall;
    private javax.swing.JButton getstatus;
    private javax.swing.JMenu info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel maleLbl;
    private javax.swing.JList<String> offlineList;
    private javax.swing.JLabel offlineUsrCountLbl;
    private javax.swing.JLabel onLbl;
    private javax.swing.JList<String> onlineList;
    private javax.swing.JLabel onlineUsrCountLbl;
    private javax.swing.JButton sendAnouncmentBtn;
    private javax.swing.JLabel serverStatusLbl;
    // End of variables declaration//GEN-END:variables
}
